import defaultTheme from 'tailwindcss/defaultTheme';

/** @type {import('tailwindcss').Config} */
export default {
	content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
	theme: {
		extend: {
			fontFamily: {
				sans: ['"Plus Jakarta Sans"', ...defaultTheme.fontFamily.sans],
			},
			colors: {
				'surface': '#f8f9fa',
				'surface-dim': '#d9dadb',
				'surface-bright': '#f8f9fa',
				'surface-container-lowest': '#ffffff',
				'surface-container-low': '#f3f4f5',
				'surface-container': '#edeeef',
				'surface-container-high': '#e7e8e9',
				'surface-container-highest': '#e1e3e4',
				'on-surface': '#191c1d',
				'on-surface-variant': '#434655',
				'inverse-surface': '#2e3132',
				'inverse-on-surface': '#f0f1f2',
				'outline': '#747686',
				'outline-variant': '#c4c5d7',
				'surface-tint': '#2151da',
				'primary': '#0037b0',
				'on-primary': '#ffffff',
				'primary-container': '#1d4ed8',
				'on-primary-container': '#cad3ff',
				'inverse-primary': '#b7c4ff',
				'secondary': '#516070',
				'on-secondary': '#ffffff',
				'secondary-container': '#d5e4f8',
				'on-secondary-container': '#576676',
				'tertiary': '#3e4555',
				'on-tertiary': '#ffffff',
				'tertiary-container': '#555c6e',
				'on-tertiary-container': '#ced5ea',
				'error': '#ba1a1a',
				'on-error': '#ffffff',
				'error-container': '#ffdad6',
				'on-error-container': '#93000a',
				'primary-fixed': '#dce1ff',
				'primary-fixed-dim': '#b7c4ff',
				'on-primary-fixed': '#001551',
				'on-primary-fixed-variant': '#0039b5',
				'secondary-fixed': '#d5e4f8',
				'secondary-fixed-dim': '#b9c8db',
				'on-secondary-fixed': '#0e1d2b',
				'on-secondary-fixed-variant': '#3a4858',
				'tertiary-fixed': '#dce2f7',
				'tertiary-fixed-dim': '#c0c6db',
				'on-tertiary-fixed': '#141b2b',
				'on-tertiary-fixed-variant': '#404758',
				'background': '#f8f9fa',
				'on-background': '#191c1d',
				'surface-variant': '#e1e3e4',
			},
			fontSize: {
				'display-xl': ['96px', { lineHeight: '100px', letterSpacing: '-0.04em', fontWeight: '800' }],
				'headline-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
				'headline-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '700' }],
				'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
				'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
				'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
				'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
				'stats-number': ['64px', { lineHeight: '72px', fontWeight: '700' }],
			},
			borderRadius: {
				'sm': '0.25rem',
				'DEFAULT': '0.5rem',
				'md': '0.75rem',
				'lg': '1rem',
				'xl': '1.5rem',
				'full': '9999px',
			},
			spacing: {
				'container-max': '1280px',
				'gutter': '24px',
				'margin-x': '64px',
				'margin-x-mobile': '20px',
				'section-gap': '120px',
				'grid-unit': '40px',
			},
		},
	},
	plugins: [],
};
